apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: data-processor
      image: data-processor
# node has to have same label prior to add below node selector.
  nodeSelector:
    size: Large