apiVersion: v1
kind: Pod 
metadata:
  name: ubuntu-sleeper-2
spec:
# to modify security context add below in spec:
  #securityContext:
    #runAsUser: 1000

  containers:
  - name: ubuntu
    image: ubuntu
    command:  
      - "sleep"
      - "3600"

      
    securityContext:
      runAsUser: 1000
      capabilities:
        add: ["MAC_ADMIN"]

  