apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004   # optional if you don`t specifty, it will be created automatically.
  selector:
    app: myapp  # need to get this from your deployment yaml file under template > labels.