apiVersion: v1
kind: Service
metadata:
  name: myapp-httpd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005   # optional if you don`t specifty, it will be created automatically.
  selector:
    type: front-end