apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: toleration
  name: toleration
spec:       # tolerations are added under spec if node has taint to match the key/value and effect.
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
  containers:
  - image: nginx
    name: toleration
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
