apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: alp
spec:
  groups:
    - system:authenticated
  usages:
    - digital signature
    - key encipherment
    - server auth
  request: 
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1V6Q0NBVHNDQVFBd0RqRU1NQW9HQTFVRUF3d0RZV3h3TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBck0yTzI2bm8zTDIxZk1QN285MHBPZ2pQempvdW9pQlQ3eWsrUVFTZ0txV0lUdlJPCjFXTVVNMDlvT0lDUlQ1eVZ1djB3V3JWRkRrRDJPalFtVzd6cGZPNHdYbE8xVTEzZ1VSamJ5ODEzQ1hkT0FDRWIKZjNhazdNYkpYR0JBdnY0RFQrajczUWZjR0Nxd25LRGNKK0E4YSszc3R2WFJRSWp4bzE0a1BZY3FjcGFEN1VEWAp5M2FKVUR2dURKaGl6WmQxcjJ2WTdSZ3hZWE9aaDVVMmU0UDFWcnB6aFJRalpMcFN1WkFEaUwxdW42eW96OUYwClJRVXlVZVBjNmRKZndhQ0FyYTN6dTJPNFBZMXAxVHFmQ2RmbWd2VGZURXlpKzl2KzVuTWZoODF6SjQwekZDVnAKNHFHS0xGUDVVcElEK3pDV0VzcG0ySUtPTGZNSld1VE5XZDc2a3dJREFRQUJvQUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFCdEJySk9VdWZQU0ZPdWVyU2R6eTZocFFITVFzUWVjQTNxdUlncjhwN2NocmZvUFFGeEdkcWRXCnEyTVNKWUxuMGtnM1RtbVpWOXVMVG9hbzdwRVgxbHpRTW8wanRYNlp6a0pMVXlxMEJDVW9mSjdxVW5DWU11U1kKOE01ZndIeWtwK2h5WG85ZUVrd21INmZmTTlWRU1ldHI5ekNaZVc0N3BSMCtnWnNwSTkxVnVCUmFybWxkdkkyTApwbUl1UDc1clBEWFE3UHZNdFFDU0lhaS9VRElCTFNoMGJnZVJHV2pmQWlFWDVQUkxhOFVVUk1IcFNpaW1UbWx3CnprZFFzMWpUTlNFd1J6aGZZUVl1Z29mUGs3OXh0NDA0MXpibWpveHZvMXN0WkhyZ1FrNndidnltWEduQUZWL2YKd3J6SmFrMHB1Zkd4VFdwNlhCOHlyNTYrbi80V3RFWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client

  # to see csr requests: kubectl get csr