apiVersion: v1
kind: Secret
data:
  DB_Host: bXlzcWw=
  DB_User: cm9vdA==
  DB_Password: cGFzc3dk
metadata:
  name: app-secret


# encode secrets run:
# echo -n 'mysql' | base64
# echo -n 'root' | base64
# echo -n 'passwd' | base64

# alternatively create using imperative commands :

# kubectl create secret generic \
# app-secret --from-literal=DB_Host=mysql  --from-literal=DB_User=root  --from-literal=DB_Password: passwd


# to view secrets : kubectl get secrets

# to view values run : kubectl get secret app-secret -o yaml